version: "3"

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9001:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb-sharded"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password123"