version: '3'

services:
  idempotent-requests-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: "mongodb://root:password123@mongodb-sharded:27017"
    ports:
      - "8080:8080"
    restart: always
    networks:
      idempotent-requests:
