version: '3'

services:
  integration-test:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    environment:
      IDEMPOTENT_REQUESTS_HOST: "http://idempotent-requests-server:8080"
    networks:
      idempotent-requests:
