name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: make test

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: docker-compose -f docker-compose.yml -f docker-compose.integration.yml up --exit-code-from integration-test
