name: Release

on:
  release:
    types:
      - published

jobs:

  tests:
    name: Release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set environment variables
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag idempotent-requests-server:$RELEASE_VERSION